// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://purfzbmejpthtbibvjxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cmZ6Ym1lanB0aHRiaWJ2anhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTk5MzMsImV4cCI6MjA2NjQzNTkzM30.L1bwOwwI2yZJvybMQpRepXVsBG-SDJAK4PEhYHeBckc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);